### ISSUE TITLE
Any plans to support Capacitor 5?

### ISSUE THREAD

**Issue by AntonERG** [ajisakson/crowdhub-plugin-flurryanalytics#1]
Any plans to support Capacitor 5?

**Comment by ajisakson** [comment]
Yes! I'm working on migrating a project to Capacitor 5 right now so I'll be adding support for that today.

**Comment by AntonERG** [comment]
Oh, that's great man!

P.S. I'm so "unhappy" with Firebase hahaha

**Comment by ajisakson** [comment]
Ok, I got it working for Android on Capacitor 5 with the latest commit. should be in npm crowdhub-plugin-flurryanalytics@5.0.0. kept the capacitor 4 version at crowdhub-plugin-flurryanalytics@4.0.0 in case anyone comes in later looking and needs support for that still. I can't test iOS yet, but will put out a 5.0.1 if I have to fix any issues when I am able to test. Will keep this issue open until I can confirm iOS working.

**Comment by AntonERG** [comment]
@ajisakson I have iPhone, will test it in the nearest days.

Let me know if you want me to test anything special.

**Comment by AntonERG** [comment]
works on iOS as well!

- build with XCode 14.3.1 with no issues
- run on iPhone with iOS 16.6
- can see app launches and events in Flurry

**Comment by ajisakson** [comment]
Awesome! Thanks for confirming. Will close the issue.
